#!/usr/bin/env bash

mktmpdir() {
  local dir=$(mktemp -t testXXXXX)
  rm -rf $dir
  mkdir $dir
  echo $dir
}

compile() {
  local fixture=$1
  shift
  local bp_dir=$(mktmpdir)
  local build_dir=$(mktmpdir)
  local cache_dir=$(mktmpdir)
  local env_dir=$(mktmpdir)
  while (( "$#" )); do
    env=("$(echo ${1} | cut -d = -f 1)")
    val=("$(echo ${1} | cut -d = -f 2)")
    echo "${val}" > "${env_dir}/${env}"
    shift
  done
  echo "env ${env_dir}: ${env[@]}"
  echo "Compiling $fixture"
  echo "in $build_dir"
  echo "(caching in $cache_dir)"
  cp -a $(pwd)/* ${bp_dir}
  cp -a ${bp_dir}/test/fixtures/$fixture/. ${build_dir}
  "${bp_dir}/bin/compile" "${build_dir}" "${cache_dir}" "${env_dir}"
}

fixture=${1:-'govendor-basic'}
r=("$@")
compile "$fixture" "${r[@]:1}"
