#!/usr/bin/env bash

mktmpdir() {
  local dir=$(mktemp -t testXXXXX)
  rm -rf $dir
  mkdir $dir
  echo $dir
}

compileSetup() {
  local fixture=$1
  shift
  while (( "$#" )); do
    env=("$(echo ${1} | cut -d = -f 1)")
    val=("$(echo ${1} | cut -d = -f 2)")
    echo "${val}" > "${env_dir}/${env}"
    shift
  done
  echo "env ${env_dir}: ${env[@]}"
  echo "Compiling $fixture"
  echo "in $build_dir"
  echo "(caching in $cache_dir)"
  cp -a $(pwd)/* ${bp_dir}
  cp -a ${bp_dir}/test/fixtures/$fixture/. ${build_dir}
}

compile() {
  local bp_dir=$(mktmpdir)
  local build_dir=$(mktmpdir)
  local cache_dir=$(mktmpdir)
  local env_dir=$(mktmpdir)
  compileSetup "${@}"
  "${bp_dir}/bin/compile" "${build_dir}" "${cache_dir}" "${env_dir}"
}

test-compile() {
  local bp_dir=$(mktmpdir)
  local build_dir=$(mktmpdir)
  local cache_dir=$(mktmpdir)
  local env_dir=$(mktmpdir)
  compileSetup "${@}"
  "${bp_dir}/bin/test-compile" "${build_dir}" "${cache_dir}" "${env_dir}"
}

test() {
  local bp_dir=$(mktmpdir)
  local build_dir=$(mktmpdir)
  local cache_dir=$(mktmpdir)
  local env_dir=$(mktmpdir)
  local artifact_dir=$(mktmpdir)
  compileSetup "${@}"
  "${bp_dir}/bin/test-compile" "${build_dir}" "${cache_dir}" "${env_dir}"
  echo
  echo "----------------------------------------------------------------------------------------------"
  echo
  "${bp_dir}/bin/test" "${build_dir}" "${env_dir}" "${artifact_dir}"
}

cmd="${1:-compile}"
shift
fixture="${1:-govendor-basic}"
shift
r=("$@")
echo "${r[@]}"
$cmd "$fixture" "${r[@]}"
