#!/usr/bin/env bash
# Copies the buildpack to a temporary location.
# if $1 is anything except "" the test directory is also copied

TMP="/tmp/buildpack_tmp."
let i=0
while [ -e "${TMP}${i}" ]; do
  let i++
done
TMP="${TMP}${i}"

function cleanUp {
  rm -rf ${TMP}
}
trap cleanUp SIGHUP SIGINT SIGTERM

function ctt {
  local fp="${1}"
  cp -a "${fp}" "${TMP}/${fp}"
}

mkdir -p ${TMP}/bin
mkdir -p ${TMP}/lib/src/github.com/apg/patter/
mkdir ${TMP}/vendor

# These are the files that are available during release
ctt bin/compile
ctt bin/detect
ctt bin/test
ctt bin/test-compile
ctt lib/common.sh
ctt lib/common_tools.sh
ctt lib/src/github.com/apg/patter/main.go
ctt lib/src/github.com/apg/patter/go.mod
ctt vendor/concurrency.sh
ctt CHANGELOG.md
ctt data.json
ctt files.json
ctt LICENSE
ctt README.md
#/end

EXTRAS="${1}"
if [ ! -z "${1}" ]; then
    mkdir -p ${TMP}/test
    tar cf - test | tar -xf - -C ${TMP}
fi

echo ${TMP}
