#!/usr/bin/env bash
#
# Fetch the files listed in data.json/test/assets (where each filename
# references a unique filename in files.json) to test/assets.
#
# This is so that `make test` can use a local bucket url (file:///test/assets).
#
set -e

# assumes we are in bin, find the directory above that
cwd="$(cd $(dirname $0); cd ..; pwd)"
df="${cwd}/data.json"
jf="${cwd}/files.json"
fc="${cwd}/file-cache"

td="${cwd}/test/assets"
mkdir -p "${td}"
cd "${td}"

shaMatchesKnown() {
    local df="${1}"
    local fn="${2}"
    local expected="$(< "${df}" jq -r '."'${fn}'".SHA')"
    local actual="$(shasum -a 256 "${fn}" | cut -d \  -f 1)"
    [ "${actual}" = "${expected}" ]
}

checkMirror() {
    local filename="${1}"
    local mirror_url="https://heroku-golang-prod.s3.dualstack.us-east-1.amazonaws.com/${filename}"
    local mirror_headers
    
    if ! mirror_headers=$(curl -sI -L --fail "${mirror_url}"); then
        echo "Error: File missing from mirror: ${mirror_url}"
        return 1
    fi

    local mirror_size=$(echo "${mirror_headers}" | grep -i content-length | awk '{print $2}' | tr -d '\r')
    local local_size=$(wc -c < "${filename}" | tr -d ' ')

    if [ "${local_size}" -ne "${mirror_size}" ]; then
        echo "Error: Mirror size mismatch for ${filename} (Local: ${local_size}, Mirror: ${mirror_size})"
        return 1
    fi
}

for f in $(< "${df}" jq -r '.test.assets[]'); do
    if [ ! -e "${f}" ]; then
        if [ -e "${fc}/${f}" ]; then
            echo "Copying ${f} from ${fc}"
            cp -a "${fc}/${f}" .
        else
            url=$(< "${jf}" jq -r '."'${f}'".URL')
            echo "Fetching ${url}"
            curl -sS -L --fail --retry 15 --retry-delay 2 --retry-connrefused --connect-timeout 5 -o "${f}" "${url}"
        fi
    fi

    if ! checkMirror "${f}"; then
        exit 1
    fi

    if ! shaMatchesKnown "${jf}" "${f}"; then
        echo "Invalid SHA for $f"
        exit 1
    fi
done
